version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8  # Możesz zmienić na inną wersję, np. node, jeżeli używasz innego języka
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make deps
      - run:
          name: Run tests
          command: make test
      - run:
          name: Build Docker image
          command: make docker_build
      - run:
          name: Push Docker image
          command: make docker_push

workflows:
  basic:
    jobs:
      - build-and-test
